spring:
  application:
    name: order

name: order
server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # health, info, metrics
  server:
    port: 9012 # http://localhost:9012/actuator
    ssl:
      enabled: false
    base-path: /
  endpoint:
    health:
      show-details: always