spring:
  application:
    name: store
  cloud:
    gateway:
      routes:
        - id: weight_high
          uri: https://example.org
          predicates:
            - Weight=group1, 8 # forward ~80% of traffic to weighthigh.org
        - id: weight_low
          uri: https://github.com # forward ~20% of traffic to weightlow.org
          predicates:
            - Weight=group1, 2

name: store
server:
  port: 9000


